name: docker-images build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 */3 * *" # At 01:00 on every 3rd day-of-month. crontab.guru

jobs:
  build-images:
    name: ovos/ci:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [gren, less, sentry, cypress12, node14]
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: build:${{ matrix.image }}
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          tags: ovos/ci:${{ matrix.image }}
          context: ${{ matrix.image }}
